parameters:
  # database connexion settings.
  database_driver: 'pdo_mysql'
  database_host: ''
  database_port: ''
  database_name: ''
  database_path: ''
  database_user: ''
  database_password: ''
  database_prefix: 'phyxo_'
  env(DATABASE_URL): null

  # IMPORTANT: You MUST configure your server version
  database_version: 1
